git:
  depth: 1
cache: yarn
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
notifications:
  slack: binary-group:xEVrYY0QGz7fbwJqi4LMWbBS
branches:
  only:
  - master
  - development
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
before_install: yarn
install: yarn test
after_success:
- git config --global user.email "arnab@binary.com"
- git config --global user.name "Arnab Karmakar"
- yarn deploy-gh-pages
env:
  global:
  - secure: ggLvaJoXEKPh7VJPnCmC5BMukaF3INrhVZwVyXJwHd0UgeUWLpwgEpL9X0GSVnEXPy3wpGkuTgjgh3U3ckCHCs9ZcMVq8nA9KYmEkOBzqnebYxqsL+RjdlrUngrLuXLas3FG84HUnx/8v3ux4/bXMfIGAzrdyMeNLvVioNsHDucfeFHzgjzCsUxU/L04lZVTNHEwdfthe6cA8BYR7KDT7zTaq06B0qFPMXMXOilw3/dbwLNsnHmiwtdjQwC6H7ohcPCSvfANDR+bLqH/o+7CFTVg9cv6401SDP2CYKjvu523Cbkr9UpCXYSRTSV3MQErLq3lKL87Zj//+TB3MnUJBccD56L6rEodQ5XJLGogT5lZDEnDOqd/kXqQIhyNLfALAW/0kBTRujr1BvNhogy7A/3jaJwZBYGDbh9wuOJNDxaldCLza8xEqBN09Bs3gEEhnUyI+45EHch9bNM+mxFOSAtqp3T+2ylCOuM5OJJlBgxrKTpNuu7w9JcSoJ+oSON7LgO5b1A0X6it3ca/bQ2gYR6nA3F020XsAzss0SO7yMNgVbB0PGY279RFyPn4UWkHterIUu/OAHg4OwDMaV00OkomP0Gb9+3FFYFjG8wUQLAPoeJVtDqb2DNFNa/ZEojN7f1EtiyqfLWKMcCu+E8Gb8Vl1R135+NGBINzeLirKM8=
  - secure: H9dAdrfhJZe+VW4CM8K+fhZlwZM1BC+UxpAoZy03WdUs+WLNGf9xjrOEC/WJVM172dkmL8amqPzSPx4lbqnFG5Id7aKu7HUfje0XlBTDldKV24K5ueO11HxiswkgzYw5OrPy6JbJfb8hZhZ80R282sSPUE5vFX8ranV30vpmuIu2lVtMtu63aSnE24OofBncgBlbHTbEga5kFE/JPdIlcA0/PztECioPt0tHKgsNGbMDFLtDLA65u9tik1qvivTEWyLtZnahVQ+iBwqSUS6LNV0CGq3l7SETiHi33ixpa+FUeiDN/YMMqZ+GHiwrpBncb5fFw796LiwgTExiJaWQPtnSsmxXyfA5nUoKHxq9PpniellBIpi5GyAe3eqy8IpZcvIgib485j1Q7cp/9WvTt2Q8OjW+PcqfSguq5ssmeDvx7z92bX967kPIvRWvCHMGLraPuznRKGkFQgkFRDLq80B2rCp8Luhz3NaakNazh++KCcfYff/gRRo3sgjz7Xb31HCBwVXUAChAwxNKnJet6qOUdOWXn+jklD4IQHXbtOq/PqkF5ZJaNv3aQAQrd+aG/NubH6kIfNuaUS8Iaz9ENcFBUBCWRSOiTje1BQEaw30uZ56VhUvDJ6ME5QhlcEz5JhG+y1Lnk4U3qbyQVflPfVOs4sAnK/MOjXNoGb2x9us=
