git:
  depth: 1
cache: yarn
matrix:
  fast_finish: true
language: node_js
node_js:
- '6'
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
  - development
script:
  - git config --global user.email "arnab@binary.com"
  - git config --global user.name "Arnab Karmakar"
  - yarn deploy-gh-pages
  - yarn test-browserstack
env:
  global:
  - secure: BA4dVZcwJrk0GhUaUcQreHR+xXlvtVEILelPXU/6+FSIe3l/JQWS09r+0NDMDvRr4BIj3MuAte7FGiTzTRvKDi2GKBHYhE7Z8tnBKmm24masTACPC2lht5XnpEatil5b7rwGWv0JrsBE3qSl0GK94X7H5lVLgshhMepg4NhK2hx7tk/17weDXgwXC/J4rzq7de9377LYhmJka2WphD8xUDIYkTSn5PuDGrLZ2gzCn6e13vcd4nn3ZIbTJkyMg2dsxZiVJ+ISagdeZ1DJ5lmnl6l+kH9c/vLfQ8h72AKkLVBn2RmR7Bv9IUDnUV5lhAekRZ9umUKp5paxXrR3thpPfztQoLqETPURqoqOhltxxVFp0N7KjKMJkZGs+eExUmoX4U1T3oe9t8fjA41bLrIJz+dF2v0afxI+fxRZc2O29IHeaFP2FVdY8SEHp+UH3dY89pU3zTo1UyCmalhCDDA8hR5VIq+HdvTTXEUceIegGue/YIr4lRZv98gMx6iSsiOTFHbPLz8N+eBbKEVRLPfIkJX8QWlBFn7r0iuFuBfCUKyvZM9KzH3gKpeQ2VcCTnLqTBM8GiWusv1icHxHQMIX0mKrvdFqkL7bH/RY6GT+7vTsyG7ZumzCS/6DOlaTaiyDAAVx5dJQtd9NAH5MgOrvOX1Z/eRO0kaATyC8Lh/8LIo=
  - secure: VUjMexRX8qZnFcrqml+ejH37CqYZ7n/YRzeytSWejXVpEP4xMC6XGc+P9VEf5nBLFn4EOIHxKHOe9/3/cPGVWvTzI6xL6n53YW47gNlhiBnPRsU2BI6uN5Mhdsm6X4zH+Rm5/KDUf5GCV0yRrif5aqeCRsmYhODAspghC12xYV+9W7BmlA7yzVfmcfbL2TScNEwKuQ78+2ciNr4EFvL53vWzlzd6EHNQnm2Um4oMYa5su/dro2xyLsiou7uIlSjqaVCsDOCMt4OJZ2EMvqg9Ms8eYlQXojoUG8sbU3C7aWNAKOxCfqKRh7FQK2xMU4YFSamqYo98Q4CCXiYScY5E/e7B4zW56aygXHf1kxpObqKrMwMIXl+vQkEm9GcNxEn126n/3RhuQW+O5Pn24RP3yugQ0WWlZzo43LR3IPpJFXoJtcW1ZLXsVPRzywnENjpCPwvH1DIJwQdKcKklUKKGsdMxo8/2sEQOQThMyko7TGL76gDZD5397IaUmS+jirGt+HD6w3ljjG8RJK6e3QpUTX1J/ygdCRdMeidEmJD1vi8nxojUYQ9ROo+DtWP5VzxJWKSMGWnY6BdociLSxzqcVk4ZmOpZMHNIYKawKS2SI4ag6j9smGTwCLlfmX5mEvB15xrJi8SRyTNFtS72I4d0iTjwj3Q9tH4Sbzk5a9OpT5M=
  - secure: G8mqpu5XaXLyiusAOlsLLFX52aq1/d5BB/enPLL4PzYJ6A/toFxxP/Az5JJdz+0JwkQQEbGSETvQt+sZyzIdMuwu9Lj/LxQP02RUvTkc0ZzfwhHn5iBFMrUsv1K+iynzzedk0jiDWBPorT/L7dq18LbYWB9AM0pZwKjcktvkvJatMjgFft7818+qi+UjRvrL/sRkXDRisS/UEQP7+42F2avUWLcoLfFir0lLLLhyJXPhSL9/ifzAneTaGm89HEfgKVQj4/qp6NSfgQsr89RHp2xAzoGQRkB1ZL45QrQPbxDIkICdqVz43kOnjb/EdaZmolimqHKEyHpCIbZSK0z0DVBv8nW2gHpsSOmOdnFTzt5b9u0wToLbUnWapIbrlzJ4O3aetSpmNh0sKp2LWCCRN8jaClTWjyiTNHC3Az7nETeygrvXP4rID5n2/BvUQWYUpgOS3WqYxL9KhhMl2kS2W+PkJZA4EYdt+JOkd5ogIGP6Jl0rSZehg8LWX1h77fY6Kq560fKSzq9yUw1kHYtbcc5debXbAkHzQ6A5gnGHg6wjPub7IOieOXFKrrCc7gSsbkF3W/KM56ko+ZSBbm1iHxxMnItWw8MkcudRMsGS/3n3hwn3W79rUDBfw028IfyRGhF14Bousw7mMYflj3/KvMcyUxAW/j0bzE9xbiN0lcc=
