language: node_js
node_js:
- '0.12'
notifications:
  email:
  - arnab@binary.com
branches:
  only:
  - master
script:
- npm install -g grunt-cli
- grunt
- sh travis_script.sh
env:
  global:
    secure: UJurrAi/wjp1pycEDH0r6QuqsCO6nWuN7JQzzzY4n0fDnoLjcycCDlDe+VrgsKRU0ApKh4pBrL3D1ruSbmdH0N9gtWtKiZiSbVYIvRPVEnOgQLvyR7LlK0yoYagACkbZsbgcWM4Rgq3vb3vG3YPXx1/ID/AdjYr+hEsa6NvbEhg=
